### PR TITLE
winerrors

### PR DESCRIPTION
**Pull request by kspawa**
@mjsabby @noahfalk This fixes build errors on Windows for the samples. If everything looks good will merge.

### CODE REVIEW

**Comment by mjsabby** [comment]
@kspawa it builds fine for me on Windows without warnings ...

**Comment by kspawa** [comment]
@mjsabby this is required for compilation on x86. x64 works without warnings. Also, removing the include paths is necessary to not include the windows.h from the pal/rt directory but use the one from the Windows sdk directory for Windows.

**Comment by mjsabby** [comment]
Wouldn't we rather use the CoreCLR SDK path? But other than (or even with that, depending on what our plan is), LGTM.

**Comment by kspawa** [comment]
Will merge this for now, once we have a concrete plan for CoreCLR SDK we can update the include paths better. Thanks!

**Pull request merged**
